#!/bin/bash
mysql_password=$(perl -mNethServer::Password -e "print NethServer::Password::store('mysql')")

# Create rest module sql tables
for i in $(ls /var/www/html/freepbx/rest/sql/*.sql); do
    mysql -uroot -p$mysql_password asterisk < ${i}
done

# Create default profile permissions only if it is needed
if [[ $(/usr/bin/mysql -B -N -uroot -p$mysql_password asterisk -e "SELECT COUNT(*) FROM rest_cti_profiles") == 0 ]] ; then
    /usr/bin/mysql -uroot -p$mysql_password asterisk < /var/www/html/freepbx/rest/sql/cti_default_permissions/cti_permissions.sql
fi

# Add column onlyForQueue to asterisk.rest_cti_profiles_paramurl
EXISTS=$(/usr/bin/mysql --defaults-file=/root/.my.cnf -e "SELECT *  FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'asterisk' AND TABLE_NAME = 'rest_cti_profiles_paramurl' AND COLUMN_NAME = 'onlyForQueue'");
if [[ $EXISTS == "" ]]; then
    $(/usr/bin/mysql --defaults-file=/root/.my.cnf -e "ALTER TABLE asterisk.rest_cti_profiles_paramurl ADD COLUMN onlyForQueue BOOLEAN default FALSE");
fi